homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lats
  longitude: !secret longs
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elev
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Indiana/Indianapolis

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret passcode
  ssl_certificate: !secret chain
  ssl_key: !secret key
  base_url: !secret url

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google

group: !include groups.yaml
recorder: !include recorder.yaml



device_tracker:
  - platform: nmap_tracker
    hosts:
      - 10.22.16.60
      - 10.22.16.63
    home_interval: 5
  - platform: owntracks
    max_gps_accuracy: 100

sensor: !include sensor.yaml
mqtt: !include emqtt.yaml
logger:
  default: warning

